// <auto-generated />
using System;
using EFCore.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCore.Repository.Migrations
{
    [DbContext(typeof(TransacaoContext))]
    [Migration("20231111011011_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EFCore.Dominio.Moeda", b =>
                {
                    b.Property<int>("IdMoeda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeMoeda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("PrecoMoeda")
                        .HasColumnType("float");

                    b.HasKey("IdMoeda");

                    b.ToTable("Moedas");
                });

            modelBuilder.Entity("EFCore.Dominio.Transacao", b =>
                {
                    b.Property<int>("IdTransacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataTrasacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeMoeda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Preco")
                        .HasColumnType("float");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TipoOperacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdTransacao");

                    b.ToTable("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
